RD /S /Q bin
RD /S /Q CWebBrowser\Debug
RD /S /Q CWebBrowser\Release
RD /S /Q CWebBrowser\Distribute
RD /S /Q EffectLib\Debug
RD /S /Q EffectLib\Release
RD /S /Q EffectLib\Distribute
RD /S /Q EterBase\Debug
RD /S /Q EterBase\Release
RD /S /Q EterBase\Distribute
RD /S /Q EterGrnLib\Debug
RD /S /Q EterGrnLib\Release
RD /S /Q EterGrnLib\Distribute
RD /S /Q EterImageLib\Debug
RD /S /Q EterImageLib\Release
RD /S /Q EterImageLib\Distribute
RD /S /Q EterLib\Debug
RD /S /Q EterLib\Release
RD /S /Q EterLib\Distribute
RD /S /Q EterLocale\Debug
RD /S /Q EterLocale\Release
RD /S /Q EterLocale\Distribute
RD /S /Q EterPack\Debug
RD /S /Q EterPack\Release
RD /S /Q EterPack\Distribute
RD /S /Q EterPythonLib\Debug
RD /S /Q EterPythonLib\Release
RD /S /Q EterPythonLib\Distribute
RD /S /Q GameLib\Debug
RD /S /Q GameLib\Release
RD /S /Q GameLib\Distribute
RD /S /Q MilesLib\Debug
RD /S /Q MilesLib\Release
RD /S /Q MilesLib\Distribute
RD /S /Q PRTerrainLib\Debug
RD /S /Q PRTerrainLib\Release
RD /S /Q PRTerrainLib\Distribute
RD /S /Q ScriptLib\Debug
RD /S /Q ScriptLib\Release
RD /S /Q ScriptLib\Distribute
RD /S /Q SpeedTreeLib\Debug
RD /S /Q SpeedTreeLib\Release
RD /S /Q SpeedTreeLib\Distribute
RD /S /Q SphereLib\Debug
RD /S /Q SphereLib\Release
RD /S /Q SphereLib\Distribute
RD /S /Q TerrainLib\Debug
RD /S /Q TerrainLib\Release
RD /S /Q TerrainLib\Distribute
RD /S /Q UserInterface\Debug
RD /S /Q UserInterface\Release
RD /S /Q UserInterface\Distribute

RD /S /Q .vs
RD /S /Q ipch
DEL /F /S /Q /A client.v12.suo
DEL /F /S /Q /A client.sdf
DEL /F /S /Q /A ..\Metin2.VC.db